spring:
  application:
    name: startup-authentication-service

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}  #510806286337-c603u13aelne23ihbjdrurgm3r8r2ibn.apps.googleusercontent.com
              client-secret: ${GOOGLE_CLIENT_SECRET}  #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
              scope: profile, email
              redirect-uri: http://localhost:8080/login/oauth2/code/google
              authorization-grant-type: authorization_code
              client-name: Google

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: ${FACEBOOK_REDIRECT_URI}
            scope: public_profile, email

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}

    datasource:
      url: jdbc:mysql://localhost:3306/startup_crm
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

  jwt:
    secretKey: ${JWT_SECRET}
    expirationMs: 3600000  # Token expiration in milliseconds (1 hour)
    refreshExpirationMs: 86400000  # Refresh token expiration (24 hours)

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # to register this service with service registry..

debug: false

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.springframework.security: WARN
